### ISSUE TITLE
Error running docker-compose up 

### ISSUE THREAD

**Issue by NotASithLord** [Monadical-SAS/oddslingers.poker#11]
Recent update fixed a number of issues on the quick start, however the last command elicits the following error:
```
yacron_1    | ZeroDivisionError: float division by zero
yacron_1    | INFO:yacron:Cron job daily-report: reporting failure
yacron_1    | INFO:yacron:Cron job daily-report: reporting permanent failure
```

**Comment by afreydev** [comment]
Hi @NotASithLord 
this error is caused basically because the app doesn't have data to be processed when you try to run it. It shouldn't avoid you start it.
I'll review it anyway. :D

**Comment by afreydev** [comment]
Hi @NotASithLord 
Effectively that error wasn't a blocker. But I've fixed the error you were getting. 
That message shouldn't be shown from now. Feel free to ask me anything you need.


![image](https://github.com/Monadical-SAS/oddslingers.poker/assets/43050896/c5fd371c-4c8a-4649-abed-a00ac800d949)
